SocialLearningPortalWeb/src/tn/esprit/piDev/socialLearningPortalWEB/managedBeans/AccountController.java
package tn.esprit.piDev.socialLearningPortalWEB.managedBeans;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;

import org.jboss.security.Base64Encoder;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.event.FlowEvent;

import tn.esprit.piDev.socialLearningPortalEJB.entitys.Account;
import tn.esprit.piDev.socialLearningPortalEJB.entitys.File;
import tn.esprit.piDev.socialLearningPortalEJB.entitys.Student;
import tn.esprit.piDev.socialLearningPortalEJB.entitys.Teacher;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.AbstractFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.FileFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.StudentFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.TeacherFacadeLocal;
import tn.esprit.piDev.socialLearningPortalWEB.utils.MD5;
import tn.esprit.piDev.socialLearningPortalWEB.utils.faces.JsfUtil;

@ManagedBean(name = "accountController")
@ViewScoped
public class AccountController extends AbstractController<Account> implements
		Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */

	// private static Logger logger =
	// Logger.getLogger(AccountController.class.getName());
	private Account account;
	private Student student;
	private String confirmPassword;
	private String passwd;
	private String oldPasswd;
	private int sexValue = 0;
	@EJB
	private StudentFacadeLocal studentFacade;
	@EJB
	private TeacherFacadeLocal teacherFacade;
	@EJB
	private FileFacadeLocal fileFacade;
	@ManagedProperty(value = "#{connectionController}")
	private ConnectionController connectionController;

	public AccountController() {
		super(Account.class);
	}

	@PostConstruct
	public void init() {
		student = new Student();
		if (connectionController.isConnected()) {
			setAccount(connectionController.getAccount());
			if(connectionController.isStudent()) student = new Student(account);
		} else {
			account = new Account();
		}
	}

	public String getCurrentImageData() {
		try {
			return Base64Encoder.encode(account.getProfilePicture()
					.getContent());
		} catch (IOException e) {
			e.printStackTrace();
			return null;
		}
	}

	public void handleFileUpload(FileUploadEvent event) {
		if (account.getProfilePicture() == null) {
			account.setProfilePicture(new File(event.getFile().getFileName(),
					event.getFile()
							.getFileName()
							.substring(
									event.getFile().getFileName()
											.lastIndexOf(".") + 1,
									event.getFile().getFileName().length()),
					event.getFile().getContents()));
		} else {
			account.getProfilePicture().setName(event.getFile().getFileName());
			account.getProfilePicture()
					.setType(
							event.getFile()
									.getFileName()
									.substring(
											event.getFile().getFileName()
													.lastIndexOf(".") + 1,
											event.getFile().getFileName()
													.length() - 1));
			account.getProfilePicture().setContent(
					event.getFile().getContents());
		}

		JsfUtil.addSuccessMessage("Success. " + event.getFile().getFileName()
				+ " is uploaded.");
	}

	public boolean save() {
		try {
			Student student = new Student(account);

			if (student.getProfilePicture() != null)
				fileFacade.create(account.getProfilePicture());

			student.setPasswd(MD5.getMD5(student.getPasswd()));

			if (sexValue == 0)
				student.setSexType(true);
			else
				student.setSexType(false);

			student.setClasse(this.student.getClasse());

			studentFacade.create(student);

			JsfUtil.addSuccessMessage("Successful registration. Please check your inbox and confirm us your e-mail address.");
			reset();
			return true;
		} catch (Exception e) {
			JsfUtil.addErrorMessage(e, "Error");
			e.printStackTrace();
			return false;
		}

	}

	public String saveChanges() {
		if (oldPasswd != null && !oldPasswd.equals("")
				&& MD5.getMD5(oldPasswd).equalsIgnoreCase(account.getPasswd())
				&& confirmPassword.equals(passwd)) {
			account.setPasswd(MD5.getMD5(passwd));
			if (connectionController.isStudent()) {
				Student student = (Student) account;
				student.setClasse(this.student.getClasse());
				studentFacade.edit(student);
			}
			if (connectionController.isTeacher()) {
				teacherFacade.edit((Teacher) account);
			}
			if (account.getProfilePicture() != null) {
				if (account.getProfilePicture().getId() != 0)
					fileFacade.edit(account.getProfilePicture());
				else
					fileFacade.create(account.getProfilePicture());
			}
			JsfUtil.addSuccessMessage("Changes saved.");
			return "/index";
		} else if (oldPasswd == null || oldPasswd.equals("")) {
			if (connectionController.isStudent())
				studentFacade.edit((Student) account);
			if (connectionController.isTeacher())
				teacherFacade.edit((Teacher) account);
			if (account.getProfilePicture() != null) {
				if (account.getProfilePicture().getId() != 0)
					fileFacade.edit(account.getProfilePicture());
				else
					fileFacade.create(account.getProfilePicture());
			}
			JsfUtil.addSuccessMessage("Changes saved.");
			return "/index";
		}
		JsfUtil.addErrorMessage("Not saved : Check your old password or password confirmation");
		return null;
	}

	public void reset() {
		try {
			account = new Account();
			student = new Student();
		} catch (Exception e) {
			JsfUtil.addErrorMessage(e, "Error");
		}

	}

	public String onFlowProcess(FlowEvent event) {
		if (event.getOldStep().equalsIgnoreCase("end")
				&& event.getNewStep().equalsIgnoreCase("confirm")) {
			return "personal";
		} else if (event.getNewStep().equalsIgnoreCase("confirm")) {
			if (account.getPasswd().equals(confirmPassword))
				return event.getNewStep();
			else {
				JsfUtil.addErrorMessage("Bad Password confirmation!");
				return event.getOldStep();
			}
		} else if (event.getNewStep().equalsIgnoreCase("end")) {
			if (!save())
				return event.getOldStep();
		}
		return event.getNewStep();
	}

	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	public int getSexValue() {
		return sexValue;
	}

	public void setSexValue(int sexValue) {
		this.sexValue = sexValue;
		if (sexValue == 0)
			account.setSexType(true);
		else
			account.setSexType(false);
	}

	@Override
	public AbstractFacadeLocal<Account> getFacade() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Account> getData() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void prepareCreate(ActionEvent event) {
		// TODO Auto-generated method stub

	}

	@Override
	public void prepareDataForStudent() {
	}

	@Override
	public void prepareDataForTeacher() {
	}

	@Override
	public void prepareDataForAdmin() {
	}

	@Override
	public boolean canEdit() {
		if (getSelectedItem() != null
				&& getSelectedItem().equals(connectionController.getAccount()))
			return true;
		return false;
	}

	@Override
	public boolean canDelete() {
		if (getSelectedItem() != null
				&& getSelectedItem().equals(connectionController.getAccount()))
			return true;
		return false;
	}

	public void setConnectionController(
			ConnectionController connectionController) {
		this.connectionController = connectionController;
	}

	@Override
	public ConnectionController getConnectionController() {
		return connectionController;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public String getPasswd() {
		return passwd;
	}

	public String getOldPasswd() {
		return oldPasswd;
	}

	public void setOldPasswd(String oldPasswd) {
		this.oldPasswd = oldPasswd;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}

SocialLearningPortalWeb/src/tn/esprit/piDev/socialLearningPortalWEB/managedBeans/AssessementController.java
package tn.esprit.piDev.socialLearningPortalWEB.managedBeans;

import java.io.Serializable;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;

import tn.esprit.piDev.socialLearningPortalEJB.entitys.Assessement;
import tn.esprit.piDev.socialLearningPortalEJB.entitys.CourseSession;
import tn.esprit.piDev.socialLearningPortalEJB.entitys.Teacher;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.AbstractFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.AssessementFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.CourseSessionFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.DocumentFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.StudentFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.TeacherFacadeLocal;

@ManagedBean(name = "assessementController")
@ViewScoped
public class AssessementController extends AbstractController<Assessement> implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	@EJB
	private AssessementFacadeLocal facade;
	
	@ManagedProperty(value = "#{connectionController}")
    private ConnectionController connectionController;
	
    private CourseSession selectedCourseSession;
	
	@EJB
	private DocumentFacadeLocal documentFacade;
	@EJB 
	private TeacherFacadeLocal teacherFacade;
	@EJB
	private StudentFacadeLocal studentFacade;
	@EJB
	private AssessementFacadeLocal assessementFacade;
	@EJB
	private CourseSessionFacadeLocal courseSessionFacade;

	public AssessementController() {
		super(Assessement.class);
	}
	
	@Override
	public AbstractFacadeLocal<Assessement> getFacade() {
		return facade;
	}
	
	public void setConnectionController(
			ConnectionController connectionController) {
		this.connectionController = connectionController;
	}
	
	public ConnectionController getConnectionController() {
		return connectionController;
	}
	
	@Override
	public void prepareCreate(ActionEvent event) {
		Assessement assessement = new Assessement();
		assessement.setCourseSession(selectedCourseSession);
		setNewItem(assessement);
	}
	@Override
	public void prepareDataForStudent() {
		// TODO Auto-generated method stub
	}
	@Override
	public void prepareDataForTeacher() {
		Assessement newItem = new Assessement();
		setNewItem(newItem);
		if(getRequestParameter("courseSessionId")!=null){
			int courseSessionId = Integer.parseInt(getRequestParameter("courseSessionId"));
			CourseSession courseSession = courseSessionFacade.find(courseSessionId);
			setData(facade.findByCourseSession(courseSession));
			
			newItem.setCourseSession(courseSession);
			recreateModel();
		}else{
			setData(facade.findByTeacher((Teacher) connectionController.getAccount()));
			recreateModel();
		}
	}
	@Override
	public void prepareDataForAdmin() {
		// TODO Auto-generated method stub
	}
	@Override
	public boolean canEdit() {
		if(getSelectedItem()!=null && getSelectedItem().getCourseSession() != null&& getSelectedItem().getCourseSession().getCreator() != null &&
				getSelectedItem().getCourseSession().getCreator().equals(connectionController.getAccount())) return true;
		return false;
	}
	@Override
	public boolean canDelete() {
		if(getSelectedItem()!=null && getSelectedItem().getCourseSession() != null&& getSelectedItem().getCourseSession().getCreator() != null &&
				getSelectedItem().getCourseSession().getCreator().equals(connectionController.getAccount())) return true;
		return false;
	}
	public CourseSession getSelectedCourseSession() {
		return selectedCourseSession;
	}
	public void setSelectedCourseSession(CourseSession selectedCourseSession) {
		this.selectedCourseSession = selectedCourseSession;
	}
	
	public String showStudents(){
		return "/pages/student";
	}
	

}

SocialLearningPortalWeb/src/tn/esprit/piDev/socialLearningPortalWEB/managedBeans/CourseController.java
package tn.esprit.piDev.socialLearningPortalWEB.managedBeans;

import java.io.Serializable;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;

import tn.esprit.piDev.socialLearningPortalEJB.entitys.Course;
import tn.esprit.piDev.socialLearningPortalEJB.entitys.Teacher;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.AbstractFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.CourseFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.CourseSessionFacadeLocal;
import tn.esprit.piDev.socialLearningPortalEJB.sessionBeans.facades.interfaces.local.DocumentFacadeLocal;

@ManagedBean(name = "courseController")
@ViewScoped
public class CourseController extends AbstractController<Course> implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	@EJB
	private CourseFacadeLocal facade;
	@EJB
	private CourseSessionFacadeLocal courseSessionFacade;
	@EJB
	private DocumentFacadeLocal documentFacade;
	@ManagedProperty(value = "#{connectionController}")
    private ConnectionController connectionController;

	public CourseController() {
		super(Course.class);
	}
	
	@Override
	public AbstractFacadeLocal<Course> getFacade() {
		return facade;
	}
	@Override
	public void prepareDataForTeacher() {
		setData(facade.findByCreator((Teacher) connectionController.getAccount()));
		recreateModel();
	}
	
	@Override
	public void prepareDataForStudent() {
		// TODO Auto-generated method stub
	}
	@Override
	public void prepareDataForAdmin() {
		// TODO Auto-generated method stub
	}
	
	@Override
	public void prepareCreate(ActionEvent event) {
		Course course = new Course();
		course.setCreator((Teacher) connectionController.getAccount());
		setNewItem(course);
	}
	
	public String showDocuments(){
		return "/pages/document";
	}
	
	public String showSessions(){
		return "/pages/courseSession";
	}

	
	public void setConnectionController(
			ConnectionController connectionController) {
		this.connectionController = connectionController;
	}
	
	@Override
	public ConnectionController getConnectionController() {
		return connectionController;
	}
	
	@Override
	public boolean canEdit() {
		if(getSelectedItem()!=null && getSelectedItem().getCreator() != null && 
				(getSelectedItem().getCreator()).equals((Teacher) connectionController.getAccount())) return true;
		return false;
	}
	@Override
	public boolean canDelete() {
		if(getSelectedItem()!=null && getSelectedItem().getCreator() != null &&
				(getSelectedItem().getCreator()).equals((Teacher)connectionController.getAccount())) return true;
		return false;
	}
	
	

}

SocialLearningPortalWeb/WebContent/pages/contact.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<ui:composition template="/template/commonLayout.xhtml">
	<ui:define name="title">SLP - Contact</ui:define>
	
	 
		
		<ui:define name="header">
		<h:form id="formHeader">
			<p:tabMenu widgetVar="tabmenu" activeIndex="2">  
    			<p:menuitem id="link0" value="Home" action="/index" icon="ui-icon-home"/>    
    			<p:menuitem id="link1" value="Register" action="/pages/register" icon="ui-icon-register" />  
    			<p:menuitem id="link2" value="Contact" action="/pages/contact" icon="ui-icon-person" /> 
    			
    			
			</p:tabMenu> 

			<p:blockUI block=":centerContainer" trigger="link0,link1,link2" autoShow="true">
        		<p:graphicImage value="/resources/images/ajax-loader.gif"/>
   			 </p:blockUI>
   			 </h:form>
		</ui:define>
		
		
	<ui:define name="left">
		
	</ui:define>
	
	<ui:define name="content">
		Contact
	</ui:define>
</ui:composition>
</html>

SocialLearningPortalWeb/WebContent/pages/profile.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<ui:composition template="/template/commonLayout.xhtml">
	<ui:define name="title">SLP - Profile</ui:define>
	
	
	<ui:define name="content">
		<h:form id="formContent" enctype="multipart/form-data" rendered="#{connectionController.connected}">
		
		<p:tabView id="tabView"> 
		
		<p:tab id="preview" title="Preview">
			<p:panel header="Preview">
			
				<h:panelGrid  columns="4" cellpadding="10">
					<h:outputText value="Firstname: " />
					<h:outputText styleClass="outputLabel"
								value="#{accountController.account.firstName}" />
					
					<h:outputText value="Lastname: " />
					<h:outputText  styleClass="outputLabel"
								value="#{accountController.account.lastName}"/>
					
					<h:outputText value="Birth Date: " />
					<h:outputText value="#{accountController.account.birthDate}" >
						<f:convertDateTime type="date" pattern="dd-MMM-yyyy"/>
					</h:outputText>
					
					<h:outputText value="Address: " />
					<h:outputText value="#{accountController.account.address}" />
					
					<h:outputText value="CIN: " />
					<h:outputText label="CIN" value="#{accountController.account.cinNumber}" />
					
					<h:outputText value="Sex: " />
					<h:outputText rendered="#{accountController.account.sexType}" value="Male"/>  
            		<h:outputText rendered="#{!accountController.account.sexType}" value="Female"/> 
        			
        			<h:outputText value="Email: " />
					<h:outputText required="true" label="Email" value="#{accountController.account.emailAddress}" />
					
					<h:outputText value="Phone: " />
					<h:outputText value="#{accountController.account.phoneNumber}"/>
        			
        			<h:outputText value="Class Name: " rendered="#{connectionController.student}"/>
					<h:outputText value="#{accountController.student.classe}" rendered="#{connectionController.student}"/>
				
					<h:outputText value="Username: " />
					<h:outputText value="#{accountController.account.username}" required="true" />
					
					<h:outputText value="Profile Picture: " />
		            <p:graphicImage  value="data:image/jpeg;base64,#{accountController.currentImageData}" rendered="#{accountController.account.profilePicture!=null}"  height="100px"  width="90px"/>
					
				</h:panelGrid>
			
			</p:panel>
			</p:tab>
		
	
		<p:tab id="personal" title="Personal">

			<p:panel header="Personal Details">
			
				<h:messages errorClass="error"/>
				
				<h:panelGrid columns="2" columnClasses="label, value" styleClass="grid">
					<h:outputText value="Firstname: *" />
					<p:inputText required="true" label="Firstname"
							value="#{accountController.account.firstName}" />
					
					<h:outputText value="Lastname: *" />
					<p:inputText required="true" label="Lastname"
							value="#{accountController.account.lastName}" />
					
					<h:outputText value="Birth Date: " />
					<p:calendar value="#{accountController.account.birthDate}" pattern="dd/MM/yyyy" />
					
					<h:outputText value="Address: " />
					<p:inputText value="#{accountController.account.address}" />
					
					<h:outputText value="CIN: " />
					<p:inputText label="CIN" value="#{accountController.account.cinNumber}" />
					
					<h:outputText value="Sex: *" />
					<p:selectOneRadio value="#{accountController.sexValue}">  
            			<f:selectItem itemLabel="Male" itemValue="0" />  
            			<f:selectItem itemLabel="Female" itemValue="1" />  
        			</p:selectOneRadio> 
					
				</h:panelGrid>
			</p:panel>
		</p:tab>
			
			
		<p:tab id="contact" title="Contact">
			<p:panel header="Contact Information">
				
				<h:messages errorClass="error"/>
			
				<h:panelGrid id="panelgrid2" columns="2" columnClasses="label, value">
					<h:outputText value="Email: *" />
					<p:inputText required="true" label="Email"
							value="#{accountController.account.emailAddress}" readonly="true" />
					
					<h:outputText value="Phone: " />
					<p:inputText value="#{accountController.account.phoneNumber}"/>
					
					<h:outputText value="Profile Picture: " />
        			<p:fileUpload fileUploadListener="#{accountController.handleFileUpload}"  
			            mode="advanced" id="fileUpload"
			            auto="true" 
			            label="Choose a file" 
			            sizeLimit="1000000"  
			            allowTypes="/(\.|\/)(gif|jpe?g|png)$/"
			            update="panelgrid2"/> 
			            
		            <h:outputText value="Preview: " rendered="#{accountController.account.profilePicture!=null}" /> 
		            <p:graphicImage  value="data:image/jpeg;base64,#{accountController.currentImageData}" rendered="#{accountController.account.profilePicture!=null}"  height="100px"  width="90px"/>
				</h:panelGrid>
			</p:panel>
		</p:tab>
		
		<p:tab id="account" title="Account">
			<p:panel header="Account Details">
			
				<h:messages errorClass="error"/>
				
				<h:panelGrid columns="2" columnClasses="label, value">
				
					<h:outputText value="Class Name: " rendered="#{connectionController.student}" />
					<p:selectOneMenu value="#{accountController.student.classe}" converter="#{classConverter}"
            		 filter="true" filterMatchMode="startsWith" effect="fade" rendered="#{connectionController.student}">  
            		 		<f:selectItem itemLabel="" />  
	            			<f:selectItems value="#{classController.facade.findAll()}" var="foo" itemValue="#{foo}"/> 
	           				 <f:converter converterId="classConverter" />  
        				</p:selectOneMenu>
				
					<h:outputText value="Username: *" />
					<p:inputText value="#{accountController.account.username}" required="true" readonly="true"/>
					
					<h:outputText value="Old Password: " />
					<p:password value="#{accountController.oldPasswd}" />
					
					<h:outputText value="Password: " />
					<p:password value="#{accountController.passwd}" />
					
					<h:outputText value="Confirm Password: " />
					<p:password value="#{accountController.confirmPassword}" />
					
				</h:panelGrid>
			</p:panel>
		</p:tab>
		
	</p:tabView>
	
	<p:commandButton action="#{accountController.saveChanges()}" value="Save" />
		
   			 
		</h:form>

	</ui:define>
</ui:composition>
</html>